package com.fractalsciences.algorithms.nlp;

public enum NLPPosType {
	NOUNS_POS, ADJECTIVES_POS, PROPER_NOUNS_POS, VERBS_POS, ADVERBS_POS, DERTERMINER_POS, PREPOSITION_POS, PRONOUN_POS, POSSESSIVE_POS, CONJUNCTION_POS, MISC_POS
}
